# Generated by Django 4.2.17 on 2025-01-25 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0002_question_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='likes',
            new_name='try_attempt',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='is_correct',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='liked_list',
        ),
        migrations.AddField(
            model_name='answer',
            name='grade',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='answer_hidden',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='question',
            name='try_limit',
            field=models.IntegerField(default=0),
        ),
    ]
