# Generated by Django 4.2.17 on 2025-01-25 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0003_rename_likes_answer_try_attempt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='grade',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='try_attempt',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='try_limit',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
