# Generated by Django 4.2.17 on 2025-01-26 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0004_alter_answer_grade_alter_answer_try_attempt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
