# Generated by Django 4.2.17 on 2025-01-26 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lesson', '0005_answer_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='feedback',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='grade',
        ),
        migrations.CreateModel(
            name='GradeFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.FloatField(blank=True, default=0, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_feedbacks', to='lesson.answer')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
