# Generated by Django 4.2.17 on 2025-01-27 20:55

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0008_alter_gradefeedback_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(blank=True, default='placeholder', max_length=255, null=True, verbose_name='image'),
        ),
    ]
